### ISSUE TITLE
How does Google's algorithm play with HTML validation?

### ISSUE THREAD

**Issue by mbalkon** [chuckreynolds/feedback#9]
I have a client who is asking me about how HTML validation plays with search. He is concerned that we need to make sure his site validates as HTML Strict with no errors in order to be viewed favorably with Google. Do you know if this is a truly significant factor for search?

**Comment by chuckreynolds** [comment]
eh.. the validation stuff won't have a great effect on rankings unless it's pretty horrible code - to the point where if it was you wouldn't need a validator to tell you it's broken. I'd focus on well coded HTML5 structure... validating is okay to do as guidance but it's definitely NOT the bible and Google doesn't consult that. You should worry about just clean structure, keep css out of html etc, and site load speeds and, of course, content and its architecture. I haven't tested a site I've built for html validation in many years. Last time I did I'm pretty sure the validators weren't even updated for HTML5 structure anyways.

Hope that helps. Cheers!

**Comment by jeremyvaught** [comment]
fwiw http://searchengineland.com/googles-matt-cutts-google-does-not-penalize-for-broken-html-172721

**Comment by mbalkon** [comment]
Thanks Chuck!

---
Melissa Balkon
Strong Design Studios
317-500-4586 *Indianapolis*
480-327-8804 *Phoenix*
480-287-9864 *Fax*
@melissabalkon
www.strongdesignstudios.com
